title: "M N Pasima - DevOps Engineer"
description: "Professional portfolio showcasing skills and experience in DevOps and Cloud Engineering."
baseurl: "/techy" # the subpath of your site
url: "https://m-pasima.github.io" # the base hostname & protocol for your site
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-archives

paginate: 5

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Skills"
    url: "/skills/"
  - title: "Experience"
    url: "/experience/"
  - title: "Education"
    url: "/education/"
  - title: "Interests"
    url: "/interests/"
  - title: "Contact"
    url: "/contact/"





