source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "minimal-mistakes-jekyll"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-paginate"
gem "jekyll-include-cache"
gem "jekyll-archives"
gem "faraday-retry"
gem "csv"
gem "base64"
gem "bigdecimal"
