source 'https://rubygems.org'
gem 'jekyll', '~> 4.2.0'
gem 'webrick', '~> 1.7'
gem 'minimal-mistakes-jekyll', '~> 4.24'
gem 'jekyll-feed'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'jekyll-include-cache'
gem 'jekyll-archives'
